spring:
  main:
    banner-mode: off

system-common:
  operation-date:
    file-path: "${SYSTEM_COMMON_OPERATION_DATE_FILE:var/operation-date.txt}"

  cluster:
    type: ha-monitor
    ha-monitor:
      monitor-path:
        command:
          - "echo"
          - "monpath ok"
        timeout: "30s"
        success-exit-codes:
          - 0

      reset-path:
        command:
          - "echo"
          - "monrp ok"
        timeout: "30s"
        success-exit-codes:
          - 0

      start:
        command:
          - "echo"
          - "monbegin ok"
        timeout: "120s"
        success-exit-codes:
          - 0

      status:
        command:
          - "echo"
          - "monshow online"
        timeout: "30s"
        success-exit-codes:
          - 0

      stop:
        command:
          - "echo"
          - "monend"
        timeout: "30s"
        success-exit-codes:
          - 0

  middleware:
    start:
      steps:
        - name: "uCosminexus Application Server"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/uas.sh start"
          timeout: "300s"
          success-exit-codes:
            - 0

        - name: "Application"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/ap.sh start"
          timeout: "300s"
          success-exit-codes:
            - 0
    check:
      steps:
        - name: "uCosminexus Application Server"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/uas.sh check"
          timeout: "300s"
          success-exit-codes:
            - 0

        - name: "Application"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/ap.sh check"
          timeout: "300s"
          success-exit-codes:
            - 0

    stop:
      steps:
        - name: "Application"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/ap.sh stop"
          timeout: "300s"
          success-exit-codes:
            - 0

        - name: "uCosminexus Application Server"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/uas.sh stop"
          timeout: "300s"
          success-exit-codes:
            - 0

  online:
    start:
      steps:
        - name: "負荷分散装置振り分け開始"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/bigip.sh start"
          timeout: "300s"
          success-exit-codes:
            - 0
    stop:
      steps:
        - name: "負荷分散装置振り分け停止"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/bigip.sh stop"
          timeout: "300s"
          success-exit-codes:
            - 0

  application:
    start:
      steps:
        - name: "uCosminexus Application Server"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/uas.sh start"
          timeout: "300s"
          success-exit-codes:
            - 0

        - name: "Application"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/ap.sh start"
          timeout: "300s"
          success-exit-codes:
            - 0

    stop:
      steps:
        - name: "Application"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/ap.sh stop"
          timeout: "300s"
          success-exit-codes:
            - 0

        - name: "uCosminexus Application Server"
          script: "echo"
          args:
            - "/etc/cmcluster/pp/uas.sh stop"
          timeout: "300s"
          success-exit-codes:
            - 0
